### ISSUE TITLE
Add command for downloading/installing the latest Arduino Firmware

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-raspberry-pi-controller#124]
So the user can do this with one click from the web application.

**Comment by RickCarlino** [comment]
:+1: Nothing in place yet, but I can start researching solutions.

**Comment by roryaronson** [comment]
Is it possible to just run a script that git clones master, ino builds, and ino uploads?

**Comment by RickCarlino** [comment]
Sure. Later on, it will be good to add stuff like rollback, cancellation and error notification (Eg: "I keep clicking the update button but nothing is happening!")

**Comment by roryaronson** [comment]
Sounds good!
