### ISSUE TITLE
Restructure messages

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-raspberry-pi-controller#129]
Right now the terminal spits out messages that look like this:

message {"devices"=>"f8700524-cd0c-49e4-b46b-3b5f5b206466", "params"=>{"speed"=>100}, "method"=>"single_command.HOME ALL", "id"=>"01758acd-1f22-4f7e-85e7-d14441c830bf", "fromUuid"=>"73425170-2660-49de-acd9-6fad4989aff6"}

I think they should be rearranged as: message {"method", "params", "devices", "fromUuid", "id"}

This ordering is more readable and accurate to the order of importance of the message contents.

**Comment by RickCarlino** [comment]
This is legacy stuff from when we were on MeshBlu.
