### ISSUE TITLE
DbAccess specs are extremely slow (db_logs_spec.rb)

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-raspberry-pi-controller#69]
I will take a look at this when time allows. Setting it here for now until that happens.

**Comment by TimEvWw** [comment]
@RickCarlino, The writing to the log also does a cleanup of old log lines.
But this seems to be very inefficient unfortunately. The cleanup could be
moved so the controller only triggers this when there is no command to
execute. Also, writing log files could be organized with log levels. But
then the log level should be written using the parameter interface,
currently not on the interface, or a (global) parameter.
